### PR TITLE
RELATED: RAIL-2775 Create the 8.3.0 version

### PR DESCRIPTION
**Pull request by no23reason**
JIRA: RAIL-2775

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/654/ : SUCCESS in 1m 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/414/ : SUCCESS in 10s

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR393

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/14/ : SUCCESS in 1m 32s (non-voting)
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/655/ : SUCCESS in 1m 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/87/ : FAILURE in 2m 50s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/180/ : SUCCESS in 23s

**Pull request merged**
