### PR TITLE
RELATED: RAIL-3048 update AttributeFilter screenshot

### PR DESCRIPTION
**Pull request by no23reason**
The component now has search bar.

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/775/ : SUCCESS in 1m 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/495/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- gooddata-ui-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gooddata-ui-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/225/ : FAILURE in 18s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR435

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/776/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/134/ : SUCCESS in 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/36/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/226/ : SUCCESS in 16s

**Pull request merged**
