### PR TITLE
RELATED: TNT-188 Chart config docs for 'enableJoinedAttributeAxisName'

### PR DESCRIPTION
**Pull request by oleg-morozov**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/982/ : SUCCESS in 1m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/653/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/998/ : SUCCESS in 1m 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/665/ : SUCCESS in 6s

**Comment by evgeniabogranskaya** [comment]
If the technical aspect is correct, OK to be merged according to the plan - fyi @no23reason

**Comment by no23reason** [comment]
Do not merge yet, merge after version 8.9.0 is released, this needs to go to 8.10.0

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR493

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Pull request merged**
