### PR TITLE
Time limit for rendering widget increased to 25mins

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**
JIRA: TNT-791

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1088/ : SUCCESS in 2m 54s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/730/ : SUCCESS in 7s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR529

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1089/ : SUCCESS in 1m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/230/ : SUCCESS in 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/125/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/320/ : SUCCESS in 23s

**Pull request merged**
