### PR TITLE
RELATED: RAIL-3808 Create version 8.7.0

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR464

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/893/ : SUCCESS in 2m 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/168/ : SUCCESS in 1m 56s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/63/ : SUCCESS in 1m 05s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/258/ : SUCCESS in 26s

**Pull request merged**
