### PR TITLE
RELATED: SD-760 Fix syntax

### PR DESCRIPTION
**Pull request by naibinh**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/309/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/148/ : SUCCESS in 6s

**Comment by ptquang86** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/310/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/149/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/311/ : SUCCESS in 33s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/150/ : SUCCESS in 3s

**Comment by lanhq** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/312/ : SUCCESS in 33s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/88/ : SUCCESS in 12s

**Pull request merged**
