### PR TITLE
Fixed example code in Dashboard Embedding article

### PR DESCRIPTION
**Pull request by andriichumak**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1198/ : SUCCESS in 1m 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/801/ : SUCCESS in 12s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR569

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1212/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/168/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/363/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/5/ : SUCCESS in 1m 07s (non-voting)

**Pull request merged**
