### PR TITLE
WEB-2986 GD.UI docs pages rebranding

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1031/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/689/ : SUCCESS in 7s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR510

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1032/ : SUCCESS in 1m 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/212/ : FAILURE in 3m 03s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/107/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/302/ : SUCCESS in 20s

**Pull request merged**
