### PR TITLE
RELATED: DX-68 Rewrite of the "About GoodData.UI" page

### PR DESCRIPTION
**Pull request by andriichumak**
* New page layout with embedding options and architecture diagram
* Moved compatibility to "Supported Versions" page

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1238/ : SUCCESS in 1m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/834/ : SUCCESS in 11s

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1239/ : SUCCESS in 1m 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/835/ : SUCCESS in 6s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR582

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1240/ : SUCCESS in 1m 09s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/173/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/368/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/10/ : SUCCESS in 53s (non-voting)

**Pull request merged**
