### PR TITLE
fix(sitemap): use the live URL

### PR DESCRIPTION
**Pull request by s-pace**
Follows algolia/docsearch#945

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/153/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 3s

**Comment by Tulean** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/315/ : FAILURE in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/154/ : SUCCESS in 6s

**Comment by no23reason** [comment]
Thank you for your help, we used the sitemap you suggested to fix our config in https://github.com/gooddata/gooddata-ui/pull/298, so I am closing this as the fix has been done on our side. Thanks again!

**Pull request closed without merging**
