### PR TITLE
RELATED: ONE-4551 Release of SDK v7.8.0

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/404/ : SUCCESS in 54s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/231/ : SUCCESS in 4s

**Comment by evgeniabogranskaya** [comment]
I checked the individual doc changes for 7.8.0 so assume that this PR covers all of them and so looks ok.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/407/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/234/ : SUCCESS in 4s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/408/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/12/ : FAILURE in 1m 54s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/104/ : SUCCESS in 14s

**Pull request merged**
