### PR TITLE
RELATED: WEB-3466 Rename GD.UI to React SDK in breadcrumbs

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1199/ : SUCCESS in 1m 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/802/ : SUCCESS in 8s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR570

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1200/ : SUCCESS in 2m 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/164/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/359/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/1/ : SUCCESS in 44s (non-voting)

**Pull request merged**
