### PR TITLE
DateFilter relativeForm documentation

### PR DESCRIPTION
**Pull request by plavemar**
- add removed status of availableGranularities in known issues
- remove availableGranularities from relativeForm options

JIRA: RAIL-1842

### CODE REVIEW

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/678/ : SUCCESS in 1m 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/429/ : SUCCESS in 16s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR401

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/679/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/98/ : SUCCESS in 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/1/ : SUCCESS in 45s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/189/ : SUCCESS in 16s

**Pull request merged**
