### PR TITLE
InsightView component documentation

### PR DESCRIPTION
**Pull request by plavemar**
- add InsightTitle properties to docs
- fix chart config docs

JIRA: RAIL-3274

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/705/ : SUCCESS in 1m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/447/ : SUCCESS in 7s

**Comment by evgeniabogranskaya** [comment]
Edit provided, LGTM

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR410

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/717/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/112/ : SUCCESS in 49s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/14/ : SUCCESS in 54s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/202/ : SUCCESS in 20s

**Pull request merged**
