### PR TITLE
8.3 language edits

### PR DESCRIPTION
**Pull request by evgeniabogranskaya**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/663/ : SUCCESS in 2m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/420/ : SUCCESS in 25s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/664/ : SUCCESS in 1m 09s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/421/ : SUCCESS in 10s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR397

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/17/ : SUCCESS in 55s (non-voting)
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/665/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/91/ : SUCCESS in 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/183/ : SUCCESS in 17s

**Pull request merged**
