### PR TITLE
RELATED: TNT-351 Update logo in AD/KD & SDK in Bear & Tiger

### PR DESCRIPTION
**Pull request by ivanmjartan**
This PR should be merge before 27th Jan release #245

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/935/ : SUCCESS in 2m 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/621/ : SUCCESS in 18s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/936/ : SUCCESS in 1m 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/622/ : SUCCESS in 11s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/937/ : SUCCESS in 1m 55s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/623/ : SUCCESS in 18s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR478

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/957/ : SUCCESS in 1m 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/191/ : SUCCESS in 1m 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/86/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/281/ : SUCCESS in 18s

**Pull request merged**
