### PR TITLE
RELATED: TNT-1075 Upgrade packages

### PR DESCRIPTION
**Pull request by pbenes**
There were problematic deps of `docusaurus`. Its deps were updated to satisfy caret versions.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1152/ : SUCCESS in 1m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/769/ : SUCCESS in 12s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR554

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1153/ : SUCCESS in 2m 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/255/ : FAILURE in 5m 19s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/150/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/345/ : SUCCESS in 1m 08s

**Pull request merged**
