### PR TITLE
RELATED: RAIL-2711 improve Create Predicates page

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/484/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/282/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/487/ : SUCCESS in 1m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/284/ : SUCCESS in 4s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/488/ : SUCCESS in 1m 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/285/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/489/ : SUCCESS in 1m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/286/ : SUCCESS in 5s

**Review by lupko — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/490/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/43/ : SUCCESS in 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/135/ : SUCCESS in 14s

**Pull request merged**
