### PR TITLE
RELATED: RAIL-4046 Move the DashboardVIew removeal to 8.10

### PR DESCRIPTION
**Pull request by no23reason**
JIRA: RAIL-4046

### CODE REVIEW

**Review by plavemar — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR498

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/997/ : SUCCESS in 1m 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/202/ : SUCCESS in 56s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/97/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/292/ : SUCCESS in 19s

**Pull request merged**
