### PR TITLE
RELATED: RAIL-4020 Improve SSO docs

### PR DESCRIPTION
**Pull request by no23reason**
* add SSO to sidebar for better searchability
* document the initiateSamlSso function

JIRA: RAIL-4020

### CODE REVIEW

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by ivanmjartan** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR495

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/986/ : SUCCESS in 1m 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/199/ : SUCCESS in 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/94/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/289/ : SUCCESS in 20s

**Pull request merged**
