### PR TITLE
RELATED: RAIL-3800 Updated the compatibility matrix

### PR DESCRIPTION
**Pull request by evgeniabogranskaya**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/878/ : SUCCESS in 1m 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/580/ : SUCCESS in 13s

**Comment by ngoc-le** [comment]
@evgeniabogranskaya , LGTM, thanks!

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR463

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/879/ : SUCCESS in 3m 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/166/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/61/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/256/ : SUCCESS in 58s

**Pull request merged**
