### PR TITLE
Reuse "viewport" option of autoresizing again

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**
JIRA: ONE-5060

Update documentation of autoresizing by new behavior of old option "viewport"

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/750/ : SUCCESS in 1m 09s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/476/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/751/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/477/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/753/ : SUCCESS in 1m 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/479/ : SUCCESS in 10s

**Review by NestorEncinas — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR425

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/755/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/125/ : SUCCESS in 45s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/27/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/216/ : SUCCESS in 17s

**Pull request merged**
