### PR TITLE
RelativeForm dimension limits issue

### PR DESCRIPTION
**Pull request by plavemar**
- information about an issue with relativeForm dimension limits

JIRA: RAIL-1526

### CODE REVIEW

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/662/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/419/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/669/ : SUCCESS in 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/424/ : SUCCESS in 10s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR396

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/19/ : SUCCESS in 1m 19s (non-voting)
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/670/ : SUCCESS in 1m 04s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/93/ : SUCCESS in 47s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/185/ : SUCCESS in 31s

**Pull request merged**
