### PR TITLE
RELATED: TNT-1151 Document new Geochart props

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**
New alternative how to define location props
JIRA: TNT-1151

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1236/ : SUCCESS in 1m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/833/ : SUCCESS in 10s

**Review by Mara3l — APPROVED** [review]
Looks good to me!

**Review by xMort — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR581

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1237/ : SUCCESS in 1m 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/172/ : SUCCESS in 1m 07s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/367/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/9/ : SUCCESS in 50s (non-voting)

**Pull request merged**
