### PR TITLE
RELATED: RAIL-2683 add boilerplate migration steps

### PR DESCRIPTION
**Pull request by no23reason**
For now the links do not make much sense, we need to wait for boilerplate's
sdk8 to be merged to master and a tag for the SDK7 version to be created.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/447/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/258/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/450/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/260/ : SUCCESS in 3s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/473/ : SUCCESS in 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/275/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/474/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/276/ : SUCCESS in 3s

**Review by lupko — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/475/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/38/ : SUCCESS in 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/130/ : SUCCESS in 13s

**Pull request merged**
