### PR TITLE
RELATED: BB-1406 basic subtotals in sdk docs

### PR DESCRIPTION
**Pull request by yanlipnican**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/7/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/11/ : SUCCESS in 41s

**Comment by evgeniabogranskaya** [comment]
@yanlipnican , will review the PR - thanks!

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/12/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/16/ : SUCCESS in 42s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/14/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/18/ : SUCCESS in 1m 01s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/15/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/19/ : SUCCESS in 29s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/5/ : SUCCESS in 31s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/20/ : SUCCESS in 57s

**Pull request merged**
