### PR TITLE
RELATED: RAIL-4665 Fixed invalid links in WebComponents docs

### PR DESCRIPTION
**Pull request by andriichumak**
Two links got mixed up.

Hey, @no23reason. When I build the project to test the fix, there is also a `website/i18n/en.json` file updated. Should I commit it as well? Thanks!

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1213/ : SUCCESS in 1m 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/811/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1214/ : SUCCESS in 1m 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/812/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1215/ : SUCCESS in 1m 04s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/813/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR573

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1216/ : SUCCESS in 1m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/169/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/364/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/6/ : SUCCESS in 46s (non-voting)

**Pull request merged**
