### PR TITLE
BUGFIX: ONE-3947 Improve Angular documentation

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/104/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/77/ : SUCCESS in 7s

**Comment by evgeniabogranskaya** [comment]
Proofread, edits made. LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/105/ : SUCCESS in 1m 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-opensource-repository-check/78/ : SUCCESS in 10s

**Comment by hangngo** [comment]
LGTM.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/106/ : SUCCESS in 2m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/31/ : SUCCESS in 17s

**Pull request merged**
