### PR TITLE
RELATED: FET-564 Sonar config

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by pbenes** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/579/ : SUCCESS in 2m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/348/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/580/ : SUCCESS in 1m 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/349/ : SUCCESS in 4s

**Comment by ivanmjartan** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-check-extended-sonar-PR379

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/1/ : SUCCESS in 39s (non-voting)

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR379

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/2/ : SUCCESS in 42s (non-voting)
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/581/ : SUCCESS in 1m 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/74/ : SUCCESS in 12s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/167/ : SUCCESS in 19s

**Pull request merged**
