### PR TITLE
TRIVIAL: move the changes made in a685038e5

### PR DESCRIPTION
**Pull request by no23reason**
The changes were made in a wrong file which would make them effective
even for older versions of SDK8 that do not support the new props.
We need to move the changes to the correct file.

Original commit: a685038e5

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/688/ : SUCCESS in 1m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/435/ : SUCCESS in 6s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR406

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/689/ : SUCCESS in 1m 55s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/102/ : SUCCESS in 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/5/ : SUCCESS in 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/193/ : SUCCESS in 44s

**Pull request merged**
