### PR TITLE
RELATED: RAIL-2814 create version 7.9.0

### PR DESCRIPTION
**Pull request by no23reason**
There are no changes in documentation, this version only bumps dependencies.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/574/ : SUCCESS in 1m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/346/ : SUCCESS in 7s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Review by lupko — APPROVED** [review]
LGTM

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/577/ : SUCCESS in 1m 27s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/72/ : FAILURE in 11m 21s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/165/ : SUCCESS in 37s

**Pull request merged**
