### PR TITLE
RELATED: WEB-1718 WEB-1719 Renaming Examples to Gallery + link fix

### PR DESCRIPTION
**Pull request by czechian**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/565/ : SUCCESS in 1m 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/339/ : SUCCESS in 7s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by no23reason** [comment]
As there are changes to the index.js which is not versioned, I suggest waiting with merging this until we are ready to release examples for the SDK 8.1.0 release so that the consistency between those and this is maintained. Is that ok @czechian?

**Comment by czechian** [comment]
@no23reason I'm OK with that

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/566/ : SUCCESS in 1m 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/69/ : FAILURE in 11m 06s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/162/ : SUCCESS in 24s

**Pull request merged**
