### PR TITLE
RELATED: Language edits related to previous PRs

### PR DESCRIPTION
**Pull request by evgeniabogranskaya**
Proofread the changes for the following PRs:

- https://github.com/gooddata/gooddata-ui/pull/472/files
- https://github.com/gooddata/gooddata-ui/pull/473/files
- https://github.com/gooddata/gooddata-ui/pull/474/files
- https://github.com/gooddata/gooddata-ui/pull/475/files

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/950/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/631/ : SUCCESS in 8s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR483

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/951/ : SUCCESS in 1m 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/188/ : SUCCESS in 40s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/83/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/278/ : SUCCESS in 19s

**Pull request merged**
