### PR TITLE
Correct last available SDK minor version.

### PR DESCRIPTION
**Pull request by kandl**
JIRA: RAIL-4502

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1150/ : SUCCESS in 3m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/768/ : SUCCESS in 9s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR553

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1151/ : SUCCESS in 2m 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/254/ : SUCCESS in 1m 33s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/149/ : SUCCESS in 2m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/344/ : SUCCESS in 37s

**Pull request merged**
