### PR TITLE
RELATED: RAIL-4416 Remove plugin limitation, they are on Cloud, too

### PR DESCRIPTION
**Pull request by no23reason**
JIRA: RAIL-4416

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR565

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1179/ : SUCCESS in 1m 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/264/ : SUCCESS in 53s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/159/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/354/ : SUCCESS in 22s

**Pull request merged**
