### PR TITLE
RELATED: RAIL-3047 take DateFilter out of beta

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by evgeniabogranskaya** [comment]
LGTM

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR409

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/704/ : SUCCESS in 1m 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/106/ : SUCCESS in 40s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/9/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/197/ : SUCCESS in 22s

**Pull request merged**
