### PR TITLE
RELATED: RAIL-2175 - First batch of documentation updates

### PR DESCRIPTION
**Pull request by lupko**
-  Split 'Getting Started' content into 'Introduction' and 'Getting Started'
-  Added Arch overview into Introduction
-  Added API Maturity & Backend Setup & Catalog Export into Getting Started
-  Reshuffled content for Custom visualizations
-  Adapted all visualizations
-  Adapt imports
-  Remove obsolete pieces

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/351/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/182/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/352/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/183/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/353/ : SUCCESS in 1m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/184/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/354/ : SUCCESS in 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/185/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/355/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/186/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/356/ : SUCCESS in 3m 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/187/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/357/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/188/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/358/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/189/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/359/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/190/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/360/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/191/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/361/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/192/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/362/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/193/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/363/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/194/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/364/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/195/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/365/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/196/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/366/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/197/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/367/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/198/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/368/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/199/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/369/ : SUCCESS in 1m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/200/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/370/ : SUCCESS in 1m 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/201/ : SUCCESS in 11s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/371/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/202/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/372/ : SUCCESS in 1m 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/203/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/373/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/204/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/374/ : SUCCESS in 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/205/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/375/ : SUCCESS in 59s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/206/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/376/ : SUCCESS in 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/207/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/377/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/208/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/378/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/209/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/379/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/210/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/380/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/211/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/383/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/213/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/398/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/226/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/399/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/227/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/409/ : SUCCESS in 1m 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/235/ : SUCCESS in 4s

**Review by no23reason — APPROVED** [review]
LGTM

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/410/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/13/ : FAILURE in 8m 28s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/105/ : SUCCESS in 15s

**Pull request merged**
