### PR TITLE
RELATED: ONE-4404 Manual resizing in PivotTable - documentation

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/329/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/164/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/330/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/165/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/331/ : SUCCESS in 1m 05s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/166/ : SUCCESS in 3s

**Comment by evgeniabogranskaya** [comment]
PR reviewed, LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/332/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/1/ : SUCCESS in 15s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/93/ : SUCCESS in 18s

**Pull request merged**
