### PR TITLE
RELATED: BB-1946 Explain over time comparison periods

### PR DESCRIPTION
**Pull request by tomassatinsky**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/242/ : SUCCESS in 1m 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/96/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/244/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/98/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/246/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/100/ : SUCCESS in 4s

**Comment by qduval** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/254/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/76/ : SUCCESS in 14s

**Pull request merged**
