### PR TITLE
BUGFIX: RAIL-2803 Update date filter docs

### PR DESCRIPTION
**Pull request by Tulean**

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR417

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/725/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/114/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/16/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/205/ : SUCCESS in 17s

**Pull request merged**
