### PR TITLE
TRIVIAL: RAIL-2944 EOS date changed for GD.UI 7.x

### PR DESCRIPTION
**Pull request by evgeniabogranskaya**
The PR is to be merged on Feb 25, 2021, together with R222.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/582/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/350/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ui-gate-PR380

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-el7/4/ : SUCCESS in 1m 13s (non-voting)
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/592/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/77/ : SUCCESS in 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/169/ : SUCCESS in 18s

**Pull request merged**
