### PR TITLE
RELATED: RAIL-2092 - Remove obsolete statement in docs

### PR DESCRIPTION
**Pull request by lupko**
JIRA: RAIL-2092

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/756/ : SUCCESS in 1m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/481/ : SUCCESS in 7s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR428

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/757/ : SUCCESS in 1m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/126/ : SUCCESS in 35s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/28/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/217/ : SUCCESS in 19s

**Pull request merged**
