### PR TITLE
TRIVIAL: Document locale prop for MVF

### PR DESCRIPTION
**Pull request by xMort**
Also, the typo was fixed for attribute filter component.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/216/ : SUCCESS in 1m 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/75/ : SUCCESS in 9s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by qduval** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/217/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/67/ : SUCCESS in 17s

**Pull request merged**
