### PR TITLE
RELATED: SD-1688 Rename project to workspace in GD.UI SDK docs

### PR DESCRIPTION
**Pull request by anvuong119**
Handle pattern projectId={projectId} → projectId={workspaceId}

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/829/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/543/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/830/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/544/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR445

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/831/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/146/ : SUCCESS in 46s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/44/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/234/ : SUCCESS in 17s

**Pull request merged**
