### PR TITLE
Can't install CGRA with node version less than v16

### PR DESCRIPTION
**Pull request by hackerstanislav**
JIRA: RAIL-4370

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1127/ : SUCCESS in 1m 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/755/ : SUCCESS in 6s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR544

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1128/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/244/ : SUCCESS in 50s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/139/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/334/ : SUCCESS in 20s

**Pull request merged**
