### PR TITLE
TRIVIAL: Attribute Filter Button vs. Attribute Filter

### PR DESCRIPTION
**Pull request by evgeniabogranskaya**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/777/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/496/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR436

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/779/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/135/ : SUCCESS in 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/37/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/227/ : SUCCESS in 18s

**Pull request merged**
