### PR TITLE
RELATED: ONE-3610 Text filter documentation

### PR DESCRIPTION
**Pull request by lupko**
Missed a couple of 'attribute filter supports URIs only'.. removed those. Added few more examples with text filters. Added re-iteration of text filter usage for simple measures (Filters set on a specific measure).

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/16/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/54/ : SUCCESS in 1m 29s

**Pull request merged**
