### PR TITLE
FEATURE: SD-683 chart alignment configuration

### PR DESCRIPTION
**Pull request by naibinh**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/148/ : SUCCESS in 1m 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/33/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/149/ : SUCCESS in 1m 07s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/34/ : SUCCESS in 7s

**Comment by evgeniabogranskaya** [comment]
Proofread - LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/150/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/35/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/151/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/40/ : SUCCESS in 17s

**Pull request merged**
