### PR TITLE
TRIVIAL: intro dashboardview -> dashboard

### PR DESCRIPTION
**Pull request by Mara3l**
Making sure the intro is up-to-date with our naming of the Dashboard component.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1250/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/843/ : SUCCESS in 4s

**Review by SubTachyon — APPROVED** [review]
Reviewed. It's... acceptable.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR586

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1251/ : SUCCESS in 1m 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/176/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/371/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/13/ : SUCCESS in 1m 42s (non-voting)

**Pull request merged**
