### PR TITLE
RELATED: MKB-3218 Add ColumnChart and MeasureValueFilter to Interacti…

### PR DESCRIPTION
**Pull request by BugsBunny338**
…ve examples

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/897/ : SUCCESS in 1m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/595/ : SUCCESS in 14s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR466

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/898/ : SUCCESS in 2m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/170/ : SUCCESS in 1m 35s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/65/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/260/ : SUCCESS in 35s

**Pull request merged**
