### PR TITLE
RELATED: MKB-3218 Add ColumnChart and MeasureValueFilter to Interactive examples

### PR DESCRIPTION
**Pull request by BugsBunny338**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/864/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/566/ : SUCCESS in 7s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- gooddata-ui-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gooddata-ui-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/250/ : FAILURE in 9s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- gooddata-ui-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gooddata-ui-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/251/ : FAILURE in 1s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- gooddata-ui-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gooddata-ui-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/252/ : FAILURE in 1s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- gooddata-ui-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- gooddata-ui-sonarqube-scan-zuul-gate : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/253/ : FAILURE in 4s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR461

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/868/ : SUCCESS in 1m 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/164/ : SUCCESS in 54s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/59/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/254/ : SUCCESS in 28s

**Pull request merged**
