### PR TITLE
RELATED: SD-1688 Rename project to workspace in GD.UI SDK docs

### PR DESCRIPTION
**Pull request by anvuong119**
Handle pattern "<projectId" → "<workspaceId" and some missing cases

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/832/ : SUCCESS in 1m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/545/ : SUCCESS in 7s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR446

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/833/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/147/ : SUCCESS in 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/45/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/235/ : SUCCESS in 18s

**Pull request merged**
