### PR TITLE
RAIL-3644 Fix syntax mistakes in result docs

### PR DESCRIPTION
**Pull request by plavemar**
JIRA: RAIL-3644

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/837/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/550/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR451

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/843/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/151/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/49/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/239/ : SUCCESS in 22s

**Pull request merged**
