### PR TITLE
RELATED: ONE-4408 Reset manual width by doubleclick on Resizer

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/335/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/168/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/336/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/169/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/337/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/170/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/338/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/171/ : SUCCESS in 3s

**Comment by evgeniabogranskaya** [comment]
Proofread - LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/339/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/173/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/340/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/3/ : SUCCESS in 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/95/ : SUCCESS in 12s

**Pull request merged**
