### PR TITLE
RELATED: ONE-4491 Update pivot table auto resizing docs

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/466/ : SUCCESS in 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/270/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/467/ : SUCCESS in 1m 31s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/271/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/468/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/272/ : SUCCESS in 3s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/485/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/283/ : SUCCESS in 5s

**Review by vlastikcz — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/493/ : SUCCESS in 38s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/45/ : SUCCESS in 15s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/137/ : SUCCESS in 12s

**Pull request merged**
