### PR TITLE
RELATED: ONE-4153 Add note about dev server browser support

### PR DESCRIPTION
**Pull request by petrjanu**
@evgeniabogranskaya, please check and correct. We are touching also historical version of docs.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/152/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/36/ : SUCCESS in 6s

**Comment by evgeniabogranskaya** [comment]
> @evgeniabogranskaya, please check and correct. We are touching also historical version of docs.

Done.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/154/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/38/ : SUCCESS in 7s

**Comment by evgeniabogranskaya** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/157/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/39/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/158/ : SUCCESS in 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/43/ : SUCCESS in 17s

**Pull request merged**
