### PR TITLE
RELATED: RAIL-4266 Introduce GoodData Cloud

### PR DESCRIPTION
**Pull request by no23reason**
Things done:
* mention GoodData Cloud along GoodData.CN and GoodData platform
* add Introduction to GoodData Cloud
* add supported versions entry for GoodData Cloud
* mention CORS settings in GoodData Cloud
* document Dashboard plugins not working in GoodData Cloud

JIRA: RAIL-4266

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1092/ : SUCCESS in 1m 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/733/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1093/ : SUCCESS in 1m 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/734/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1094/ : SUCCESS in 1m 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/735/ : SUCCESS in 16s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1095/ : SUCCESS in 2m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/736/ : SUCCESS in 14s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR531

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1096/ : SUCCESS in 1m 27s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/231/ : FAILURE in 2m 10s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/126/ : SUCCESS in 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/321/ : SUCCESS in 23s

**Pull request merged**
