### PR TITLE
Update 15_props__error_component.md

### PR DESCRIPTION
**Pull request by andriichumak**
Minor changes to the example code

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- gooddata-ui-documentation-validation : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/548/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 13s

**Comment by plavemar** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/838/ : SUCCESS in 1m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/551/ : SUCCESS in 9s

**Review by plavemar — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR449

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/842/ : SUCCESS in 1m 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/150/ : SUCCESS in 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/48/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/238/ : SUCCESS in 18s

**Pull request merged**
